name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "===== Connected to EC2 ====="
            whoami
            hostname

            echo "===== Moving to project ====="
            cd /home/ubuntu/docker-cloud-practice/cloud-api-ci-cd-test-
            pwd

            echo "===== Pulling latest code ====="
            git pull origin main

            echo "===== Latest commit ====="
            git log -1 --oneline

            echo "===== Building Docker image ====="
            docker build --no-cache -t docker-ec2-cloud-api:latest .

            echo "===== Stopping old container ====="
            docker stop ec2-docker-cloud-practice-api || true

            echo "===== Removing old container ====="
            docker rm ec2-docker-cloud-practice-api || true

            echo "===== Starting new container ====="
            docker run -d \
              --env-file .env \
              --name ec2-docker-cloud-practice-api \
              -p 3000:3000 \
              docker-ec2-cloud-api:latest

            echo "===== Running containers ====="
            docker ps

            echo "===== Testing application ====="
            sleep 3

            curl http://localhost:3000
            echo

            curl http://localhost:3000/health
            echo

            echo "===== Deployment successful ====="