name: Build, Push and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: cloud-api-practice-repo
  ECR_REGISTRY: 029637202653.dkr.ecr.eu-north-1.amazonaws.com
  CONTAINER_NAME: ec2-docker-cloud-practice-api
  CONTAINER_PORT: 3000

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # --------------------------------
      # 1. Checkout
      # --------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------------------
      # 2. Configure AWS using OIDC
      # --------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::029637202653:role/GitHubActions-ECR-Push-CloudAPI
          aws-region: ${{ env.AWS_REGION }}

      # --------------------------------
      # 3. Login to ECR
      # --------------------------------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # --------------------------------
      # 4. Build Docker image
      # --------------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
            .

      # --------------------------------
      # 5. Push image to ECR
      # --------------------------------
      - name: Push Docker image
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      # --------------------------------
      # 6. Deploy to EC2
      # --------------------------------
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "================================"
            echo "Connected to EC2"
            echo "================================"

            whoami
            hostname

            echo "================================"
            echo "Logging into ECR"
            echo "================================"

            aws ecr get-login-password \
              --region eu-north-1 | \
              docker login \
              --username AWS \
              --password-stdin \
              029637202653.dkr.ecr.eu-north-1.amazonaws.com

            echo "================================"
            echo "Pulling new Docker image"
            echo "================================"

            docker pull \
              029637202653.dkr.ecr.eu-north-1.amazonaws.com/cloud-api-practice-repo:${{ github.sha }}

            echo "================================"
            echo "Stopping old container"
            echo "================================"

            docker stop ec2-docker-cloud-practice-api || true

            echo "================================"
            echo "Removing old container"
            echo "================================"

            docker rm ec2-docker-cloud-practice-api || true

            echo "================================"
            echo "Starting new container"
            echo "================================"

            cd /home/ubuntu/docker-cloud-practice/cloud-api-ci-cd-test-

            docker run -d \
              --env-file .env \
              --name ec2-docker-cloud-practice-api \
              -p 3000:3000 \
              029637202653.dkr.ecr.eu-north-1.amazonaws.com/cloud-api-practice-repo:${{ github.sha }}

            echo "================================"
            echo "Running containers"
            echo "================================"

            docker ps

            echo "================================"
            echo "Health check"
            echo "================================"

            sleep 3

            curl --fail http://localhost:3000/health

            echo
            echo "================================"
            echo "DEPLOYMENT SUCCESSFUL"
            echo "================================"